### ISSUE TITLE
[Question] Why the "privileged: true"  exists in es yaml.

### ISSUE THREAD

**Issue by xiaoping378** [kayrus/elk-kubernetes#1]
![image](https://cloud.githubusercontent.com/assets/5623173/19509118/be3e55fc-960f-11e6-8b19-7edb740e1efd.png)
I have removed the securityContext section, it will be run successfully. So why we need it.

**Comment by kayrus** [comment]
Short answer it: "The securityContext must be set to privileged and the IPC_LOCK capability enabled to allow Elasticsearch to lock the heap in memory so it won’t be swapped."

Most probably this is a legacy inherited code, but I'd recommend you to test elasticsearch under heavy load and try to swap the node. Most probably it'll work fine.

**Comment by kayrus** [comment]
`privileged` is necessary to resolve this issue: https://github.com/kubernetes/charts/blob/master/incubator/elasticsearch/README.md#mlocking
https://github.com/kubernetes/kubernetes/issues/3595
