### ISSUE TITLE
es-number-of-replicas in es-env don't work

### ISSUE THREAD

**Issue by xiaoping378** [kayrus/elk-kubernetes#2]

**Comment by kayrus** [comment]
any details? did you bootstrap a brand new cluster? or you already had existing indices?

**Comment by kayrus** [comment]
I have two clusters with 1 and 2 replicas. Here is the info.
![screenshot_20161019_112344](https://cloud.githubusercontent.com/assets/4047483/19512971/9f0f87c6-95ee-11e6-84ae-f90c3cc0e444.png)
![screenshot_20161019_112406](https://cloud.githubusercontent.com/assets/4047483/19512972/9f1263a6-95ee-11e6-9d61-0c2ed1b8567c.png)

**Comment by xiaoping378** [comment]
bootstrap a new cluster. 
![image](https://cloud.githubusercontent.com/assets/5623173/19513143/8046e892-9621-11e6-9efb-804a4a40ccac.png) is decided by ES_DATA_REPLICAS in deploy.sh

**Comment by kayrus** [comment]
Looks like you've mixed up elasticsearch indices replicas and elasticsearch pods replicas in Kubernetes deployment.

**Comment by xiaoping378** [comment]
Sorry, i mixed.

**Comment by xiaoping378** [comment]
can you rm *.yaml_ in the project ?
I did not find it is useful ...

**Comment by kayrus** [comment]
It is useful for users who will want to split data/master. I have to update them though...

**Comment by xiaoping378** [comment]
YES. Thank you very much.
