### ISSUE TITLE
-o jsonpath={.items[0].metadata.name} can't work in zsh

### ISSUE THREAD

**Issue by xiaoping378** [kayrus/elk-kubernetes#3]
i am using oh-my-zsh, kubectl -o jsonpath={.items[0].metadata.name} can't get anything.
Switch to bash, it will get the correct result.
can you make it work in zsh ?

**Comment by kayrus** [comment]
Thanks for report. Try to use double quotes:

```
kubectl -o jsonpath="{.items[0].metadata.name}"
```

**Comment by xiaoping378** [comment]
added double quotes, it is OK.
Thank you very much.

**Comment by kayrus** [comment]
Will be fixed soon in master branch. Working on a bunch of fixes.

**Comment by ulises-castro** [comment]
Did you fix this issue guys? I have latest version of zsh and it is still there.

**Comment by zl0ty** [comment]
@ulises-castro 
> Did you fix this issue guys? I have latest version of zsh and it is still there.

I still have this issue. But seems that I was able to fix it by commenting out `unsetopt PROMPT_SP` in `~/.zshrc`. I don't know what will be the issues that this follows it, but so far it looks fine.
