### ISSUE TITLE
ES-Data pods not starting up

### ISSUE THREAD

**Issue by peteyycz** [kayrus/elk-kubernetes#4]
I've encountered the same issue as mentioned here, https://github.com/pires/docker-elasticsearch-kubernetes/issues/5 is there any easy way of changing the elasticsearch configuration without using another docker container?

**Comment by kayrus** [comment]
@peteyy you can easily define `NETWORK_HOST` environment variable in es-data* yaml files.

`elasticsearch.yml` files already cointain this string:

```yaml
network.host: ${NETWORK_HOST}
```

**Comment by peteyycz** [comment]
But for that I'll need to rebuild the image right?

**Comment by kayrus** [comment]
@peteyy no, just add an extra environment variable into the yaml file.

**Comment by peteyycz** [comment]
Thanks, it works now!
