### ISSUE TITLE
error in es-master pods on deploy

### ISSUE THREAD

**Issue by anodyne4j** [kayrus/elk-kubernetes#6]
Trying to deploy this to a 1 master, 2 node k8s 1.5.1 cluster on AWS, and the es-master pods are crashing. kubectl logs shows the following error:

"Exception in thread "main" java.lang.IllegalArgumentException: No up-and-running site-local (private) addresses found, got [name:lo (lo), name:eth0 (eth0)]"

Both nodes and masters are running Debian jessie.

Any help you can offer would be much appreciated.

**Comment by kayrus** [comment]
please refer to #4 issue. you have to define extra environment variable inside the yaml file.

**Comment by anodyne4j** [comment]
Thanks so much! That worked perfectly.
